Vagrant is a tool for building and managing virtual machine environments in a single workflow. With an easy-to-use workflow and focus on automation, Vagrant lowers development environment setup time, increases production parity, and makes the "works on my machine" excuse a relic of the past.

https://www.vagrantup.com/


== Interesting Vagrant Boxes

https://app.vagrantup.com/ubuntu/

	ubuntu/bionic64 - 319MB Official Ubuntu 18.04 LTS (Bionic Beaver)
	ubuntu/trusty64 - 427MB Official Ubuntu Server 14.04 LTS (Trusty Tahr)

https://app.vagrantup.com/centos
	
	centos/7 CentOS Linux 7 x86_64 Vagrant Box

https://app.vagrantup.com/zemiandeng

	zemiandeng/ubuntu-18.04 - 1.4GB based on "ubuntu/bionic64"
		This includes developer tools mentioned here in Getting Started section.


== Getting Started on Windows 10

NOTE: These installs requires admin elevated rights.

1. Download and install VirtualBox
2. Install Vagrant
3. Setup Ubuntu VM
----
mkdir -p ~/vm/ubuntu/bionic64
cd ~/vm/ubuntu/bionic64
vagrant init ubuntu/bionic64
vagrant up
vagrant ssh

If config `Vagrantfile` is updated you can reload like this
vagrant reload

# To stop the vm, run this
vagrant halt

# Ensure all packages are up-to-date
$ sudo apt update

# To switch to root user
$ sudo su -
----

=== Installing Softare

----
# System tools
sudo apt install -y zip unzip


# JDK
sudo apt install -y default-jdk
sudo apt install -y openjdk-8-jdk

	# To switch to different jdk
	sudo update-alternatives --config java

	NOTE Ubuntu named `/usr/lib/jvm/java-11-openjdk-amd64` but it
	actually is a JDK version 10!


# Java/Spring Dev Setup
wget https://repo.spring.io/release/org/springframework/boot/spring-boot-cli/2.1.3.RELEASE/spring-boot-cli-2.1.3.RELEASE-bin.zip
unzip spring-boot-cli-2.1.3.RELEASE-bin.zip

	# Setup a Java Project For Dev
	spring-2.1.3.RELEASE/bin/spring init -d=web --build=gradle ~/src/zemian/hello-web
	cd ~/src/zemian/hello-web
	./gradlew bootRun


# Database - MySQL
sudo apt install -y mysql-server

	# Verify
	sudo mysqladmin -p -u root version

	# Access client
	sudo mysql

	# To change root user password
	ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root123';
	FLUSH PRIVILEGES;
	SELECT user,authentication_string,plugin,host FROM mysql.user;

	# To create new db user and database
	# By using GRANT, no need to flush privileges
	CREATE DATABASE zemiandb;
	CREATE USER 'zemiandb'@'localhost' IDENTIFIED BY 'zemiandb123';
	GRANT ALL PRIVILEGES ON zemiandb.* TO 'zemiandb'@'localhost' WITH GRANT OPTION;

	# To connect to zemiandb
	sudo mysql -u zemiandb -p zemiandb

	# To restart the db
	sudo systemctl restart mysql
	sudo systemctl status mysql

	# To disable auto start of the service
	sudo systemctl stop mysql
	sudo systemctl disable mysql


# Database - Postgres
sudo apt install -y postgresql postgresql-contrib

	# To access the client
	# Or run psql without switch user
	sudo -u postgres psql

	# To add new DB and unix user
	sudo adduser zemiandb
	sudo -u postgres createuser -s zemiandb
	sudo -u zemiandb createdb zemiandb

	# To connect to zemiandb
	sudo -u zemiandb psql

	# To restart the db
	sudo systemctl restart postgresql
	sudo systemctl status postgresql


# Web server: nginx
sudo apt install -y nginx
sudo systemctl status nginx


# Setup C compiler
sudo apt install -y build-essential

----

== How to expose VM (Guest) port to host (Windows)

Enable port_forward in Vagrantfile.

== References

* https://www.vagrantup.com/docs/index.html
* https://www.digitalocean.com/

== How to export Vagrant box and reuse it

----
cd ~/vm/ubuntu/bionic64
vagrant package --output=ubuntu-18.04 --vagrantfile=Vagrantfile

----
